version: '3'
services:
  client:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.develop 
      args:
        port: 3000
    restart: always
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: database:27017
  