FROM node:10.12.0-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
WORKDIR /home/react/app
ENV NODE_ENV dev
COPY package*.json ./
RUN npm install
ARG port=3000
EXPOSE 3000
COPY . ./
CMD /wait && npm start