version: '3'
services:
  backend:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.production 
      args:
        port: ${PORT}
    env_file:
      - ../.env
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      WAIT_HOSTS: database:27017
  database:
    image: mongo
    env_file:
      - ../.env
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"